apiVersion: v1
kind: PersistentVolume
metadata:
  name: kkal-tracker-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/kuber/kkal-tracker/data"
